### ISSUE TITLE
Revoke Access does not revoke access

### ISSUE THREAD

**Issue by thomasfw** [restrictcontentpro/restrict-content-pro#1043]
If I select 'revoke access' from the bulk options tool on the member list, that user just has their status changed to 'cancelled', it doesn't revoke their access at all (they retain access until their expiry date is reached).

If a member cancels their membership in return for a full refund for example, we need the ability to completely revoke the membership.

**Comment by mindctrl** [comment]
We could rename the option to what it really does, which is something like `Mark as Cancelled`.

In the meantime, you can set them as expired or pending to actually remove access if you've done a refund.

**Comment by nosegraze** [comment]
Maybe we should add a refunded status.

**Comment by pippinsplugins** [comment]
I'm not sure a refunded status works. What if a member has 4 payments and 3 are complete but one is refunded. Does that give them a refunded status?

**Comment by nosegraze** [comment]
Hmm that is a good point.

I guess I can just see some confusion with manually revoking access. There's not really a super great way to do that. The two options are:

1. Change status to "Expired" or "Pending". This would immediately do the trick, but I feel like the status names aren't super applicable to what's being done in this case.
2. Change status to "Cancelled" (very applicable to this case), but then that _also_ requires manually updating the expiration date.

I can see the appeal of a better solution that only requires one change rather than two.

**Comment by mindctrl** [comment]
At first glance I like option 2. Set to cancelled and adjust the expiration date to today 00:01 or something like that. However, when we support multiple concurrent subscriptions that won't really work. In fact, the option probably won't even make sense at all, as I imagine most people won't want to revoke all subscriptions... and bulk update won't provide a UI for selecting the subscription to revoke.

**Comment by nosegraze** [comment]
I imagine with multiple memberships all the status labels will be moved to the subscriptions rather than to the user.

TBH, it might just be nice if when updating a status to "Cancelled" they also get a checkbox to "Revoke access now" and if that's checked we update the expiration date for them to something in the past.

**Comment by pippinsplugins** [comment]
>>>"Revoke access now" and if that's checked we update the expiration date for them to something in the past.

I like this approach.

**Comment by nosegraze** [comment]
PR: #1115

Adds the revoke access checkbox on bulk edit and individual "Edit Member" screen.

**Comment by pippinsplugins** [comment]
Looks good here!
