### ISSUE TITLE
Add support for multiple levels in register form shortcode

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#1187]
Example:

`[register_form id="1,2,3"]`

**Comment by nosegraze** [comment]
PR: #1188

**Comment by mindctrl** [comment]
Passing comma separated values into `rcp_registration_form_fields()` changes the signature of the data that is passed into both the function and the action hooks inside it.

The phpdoc for `@param $id` says it takes `null|int`. We can obviously control what we pass into it, but not what others are doing.

Specifically I see this being an issue for the hooks:
`do_action( 'rcp_before_register_form', $id );`
`do_action( 'rcp_after_register_form', $id );`

Anyone tying into this now won't be aware of the signature change.

**Comment by nosegraze** [comment]
It shouldn't hurt any existing code unless someone actually starts using the shortcode this way, so it's not like they'll upgrade and all their code will break. I'd be fine with just adjusting the docs.

**Comment by pippinsplugins** [comment]
I vote we adjust the docs.

**Comment by mindctrl** [comment]
The hooks have had the `$id` arg in place for 3 years, and there's no way to know how they're being used - whether that's a custom integration or add-ons we don't know about. Changing the data type passed to it is a breaking change.

A couple thoughts.

1) Only fire the hooks if `$id` is null or a numeric. This would keep the same functionality we have now, **but** it would be unexpected behavior to conditionally fire the hooks based on the data passed in. Problematic if someone decides to add another level to their form and their add-on doesn't work, but not as problematic as changing the data type passed into the hook.

2) Introduce a new `ids` parameter in the shortcode and use it instead of changing the `id` parameter. We could then maybe add `$atts['ids']` to the action hooks to allow integrations to take this into account.

Other ideas?

**Comment by pippinsplugins** [comment]
I like approach two better, I think.

**Comment by mindctrl** [comment]
Instead of passing `$atts['ids']`, we could just go ahead and pass the whole `$atts` array.

**Comment by nosegraze** [comment]
Updated the PR to use `ids` attribute instead. We can include the whole `$atts` array in the action if you want, though it's also available in a global variable.

**Comment by nosegraze** [comment]
Added it https://github.com/restrictcontentpro/restrict-content-pro/commit/897394bf5e9624c5bd9f632b6260823c46f9967c

**Comment by pippinsplugins** [comment]
I like this approach. PR looks good to me.
