### ISSUE TITLE
Add renewal payment failed email notification template for admins

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#1246]
Got a request for this from a customer. We only have a template for members - not admins.

**Comment by pippinsplugins** [comment]
This is for an email notification, right?

**Comment by nosegraze** [comment]
Yep!

**Comment by mindctrl** [comment]
A template or just a setting?

**Comment by nosegraze** [comment]
At least a setting, though I suspect if we add a setting without a template, we'll start getting requests to customize the message, so I'd add a template as well.

**Comment by nosegraze** [comment]
Got another request for this.

**Comment by nosegraze** [comment]
PR: #1566 

I still need to test this.

**Comment by tnorthcutt** [comment]
+1 for this, I have a current client request for this. Looks like the PR is filterable as per https://github.com/restrictcontentpro/restrict-content-pro/issues/1497, thanks!

**Comment by mindctrl** [comment]
In my tests of #1566 with Stripe, the email doesn't send. It appears to be caused by [this conditional](https://github.com/restrictcontentpro/restrict-content-pro/blob/2.9.6/includes/gateways/class-rcp-payment-gateway-stripe.php#L705) being incorrect, so `rcp_recurring_payment_failed` doesn't fire.

It my test, the conditional should be:
`if ( ! empty( $event->data->object->subscription ) && ( $event->data->object->subscription == $member->get_merchant_subscription_id() ) ) {`

The difference being the `data` object in there.

Also, the admin subject setting gets overwritten by whatever is in the member subject when saved.

**Comment by nosegraze** [comment]
Fixed the issue with the subject.

Will look into that conditional in a bit.

**Comment by nosegraze** [comment]
Updated. Both issues should be fixed now.
