### ISSUE TITLE
User role not re-applied to expired user who gets reactivated

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#1257]
This would only happen if the user expires and then their membership gets reactivated without them going through the registration form. Here's an example scenario a customer had:

- Have custom role applied via subscription level.
- User signs up for recurring subscription via Stripe and gets the custom role on their account.
- User's account expires due to failed payment / expired card. The custom role is removed.
- They're using Baremetrics Recover and the user updates their card details that way.
- The card gets updated in Stripe, Stripe processes the payment, and the account gets reactivated.
- But the custom role is never reapplied.

**Comment by josephsellers** [comment]
Here is another scenario where this is a problem. You can set Stripe so that it automatically retries payments a number of times after a failure. Sometimes a failed payment is later successfully processed. 

So, the process is similar but not the same. Here are the steps @nosegraze  outlined but with the variation in bold:

- Have custom role applied via subscription level.
- User signs up for recurring subscription via Stripe and gets the custom role on their account.
- User's account expires due to failed payment / expired card. The custom role is removed.
- **Stripe retries the payment and a successful payment goes through.**
- **Stripe processes the payment, and the account gets reactivated.**
- But the custom role is never reapplied.

**Comment by chrisvanpatten** [comment]
Is the issue exclusively that the custom role isn't reapplied? But the user would still be re-added in the correct subscription level after reactivating?

I have a client considering Baremetrics Recover and this issue came up while searching how RCP and Recover would interact. We don't use custom roles however, so if the issue is just limited to custom roles we should be safe.

**Comment by nosegraze** [comment]
@chrisvanpatten  This issue is limited to the WordPress user role (i.e. `subscriber` or `editor` or any custom role). It does not affect the RCP subscription level. So if you don't use roles to grant users additional privileges or restrict content according to role rather than RCP subscription level then you wouldn't be affected by this problem.

**Comment by mindctrl** [comment]
I think this is an issue with most/all of the gateways.

We could update `RCP_Member::renew()` to update the role, since it already handles updating expiration, status, recurring status, and renewed date, and I think that would cover all the gateways.

**Comment by nosegraze** [comment]
PR: #1520
