### ISSUE TITLE
Utility function for getting all current members

### ISSUE THREAD

**Issue by thomasfw** [restrictcontentpro/restrict-content-pro#1272]
There's no easy way to list all current members, including those who have cancelled but not yet expired. We run on a yearly membership - if a member cancels their auto renewal in the first few months, they're still considered a member until their expiry date it reached as you'd expect. The cancelled but non-expired members are not included in `rcp_get_members( 'active' )`, yet they're considered members when they're checked with`RCP_Member->can_access()`, `RCP_Member->is_active()` and similar functions. 

A utility function similar to rcp_get_members() like the one below would be really useful:

```php
function rcp_get_members_with_access( $offset = 0, $number = 999999, $order = 'DESC', $search = '' ) { /* Return active and cancelled but non-expired members */ }

```

Are you any closer on deciding whether or not to expire cancelled users when their expiration date is reached? Doing so would also simplify the above function as you'd just combine the `cancelled` and `active` lists without needing to do further expiration date meta checks for each record.

**Comment by pippinsplugins** [comment]
@thomasfw you can use the `rcp_get_members()` function to do this:

```php
$members = rcp_get_members( 'active', null, 0, 9999999, 'DESC', null );
```

**Comment by nosegraze** [comment]
I'd rather improve `rcp_get_members()` rather than make a whole new function. For example, we could:

- Allow for the `$status` parameter to accept an array.
- Add another parameter for checking the expiration date (maybe similar to how you'd do a date query).

But I think we should wait until we introduce a custom table for members before we make any changes. The custom table will allow us to query much more efficiently. I'd also love to replace all those parameters with a single `$args = array()` parameter.

**Comment by thomasfw** [comment]
Okay no problem, i'll roll with a custom query for now then
