### ISSUE TITLE
Pending members count incorrect

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#1442]
When a member signs up with the manual payment gateway and their status remains as pending, the pending count is incorrect in the admin list.

**Comment by mindctrl** [comment]
We don't set `rcp_pending_subscription_level` usermeta on registration right now, and I don't recall why or if it was on purpose, but that's why pending member count isn't updated in `rcp_increment_subscription_member_count_on_status_change()`.

There's no pending level, and there's no sub_id on the user yet, so the logic fails to update the count.

It was removed in #1000. @nosegraze do you remember if that was intentional?

**Comment by nosegraze** [comment]
I think simply because it wasn't needed anymore and for backwards compatibility in `RCP_Member:;get_pending_subscription_id()` we use the pending payment record to get the pending payment.

I think the core problem here is that the user's status gets set to `pending` during registration _before_ the pending payment record is created. That's why this ends up being `false` : 

```php
$pending_sub_id = $member->get_pending_subscription_id();
```

The pending payment record would simply need to be created before the status is set.

**Comment by mindctrl** [comment]
PR: #1579 

We need to test to make sure this doesn't have unintended consequences. We've made several changes over the last year to the registration flow due to timing issues.
