### ISSUE TITLE
PHP notice: Undefined property: RCP_Emails::$payment_id

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#1452]
In #1441 we removed the `$payment_id` property, but it's still being called by `do_tag()`. https://github.com/restrictcontentpro/restrict-content-pro/blob/2.9.4/includes/class-rcp-emails.php#L510

**Comment by nosegraze** [comment]
Two options:

1) Remove all traces of `$payment_id` from the `RCP_Emails` class. This means any time `%amount%` is used, it will query for the amount of the latest payment inside the tag function. This is how it's used in core and what we describe it as doing.
2) We keep the `$payment_id` property in `RCP_Emails`, which allows a developer greater flexibility, because they could technically set the `$payment_id` to anything else they wanted when creating custom emails, and thus allow `%amount%` to be for a different payment other than the latest one.

**Comment by mindctrl** [comment]
Hmm. We could add the property back, and if someone needs it to be set, they'll be able to set it directly since there's a `__set()` method. Defeats one of the main purposes of private properties, which it was (and the others are too), but it's been that way so we might as well run with it. Option 2 sounds like the better plan.

**Comment by pippinsplugins** [comment]
I prefer 2.

**Comment by nosegraze** [comment]
Merged.
