### ISSUE TITLE
BUG: since the upgrade the plugin create 0$ peyments

### ISSUE THREAD

**Issue by ramiy** [restrictcontentpro/restrict-content-pro#1499]
We have upgraded RCP from an old version to 2.9.4. The new version has an annoying bug. When a new user create a free account (Price 0$ ; Fee 0$ ; unlimited duration), it creates a new **payment** record:

![bug](https://user-images.githubusercontent.com/576623/31584737-7d44ded0-b1bc-11e7-891f-99845ec9dffd.png)

The expected behavior is to create new payment only when the amount is higher than 0$, not on every new subscription registration.

**Comment by bainternet** [comment]
Same issue here, we use the `rcp_insert_payment` action hook which is now triggered on $0 payments.

**Comment by maor** [comment]
+1 that seems like a bug over here as well.

**Comment by nosegraze** [comment]
This is actually intentional. :) In `2.9` we started creating payment records even for `$0` registrations. Our thought was that having the `$0` payments could serve as a form of "record keeping" any time there's a registration. Plus with the new information we're storing with payments (like discount codes) it can be a better way of illustrating how a registration came to be free.

**Comment by ramiy** [comment]
@nosegraze @pippinsplugins Can I deactivate this "feature"?

If not, Is there a filter that can be used to check the amount before generating the payment record?

**Comment by nosegraze** [comment]
@ramiy We don't have a way to deactivate the payment generation because our whole process actually relies on the payment being there. The flow works like this:

1. Click "Register" button during registration.
2. Create `pending` payment with all associated subscription date (corresponding level, discount code used, etc.).
3. Additional form processing stuff.
4. Then the way the subscription is finally activated is by updating the pending payment's status to `complete`. This triggers another action that finally adds the subscription level to the user and activates the membership.

So stopping the payment generation to begin with would break that whole process (mainly step 4 because a payment is expected there). You could theoretically hook into something like `rcp_update_payment_status_complete` to delete the payment after the fact. You just want to make sure it has a high priority so it gets triggered after our `rcp_complete_registration` function that hooks into the same thing. I don't foresee any issues with doing this.
