### ISSUE TITLE
Gateway name is logged in rcp_process_registration() on free registrations.

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#1556]
On totally free registrations, `rcp_process_registration()` is logging PayPal as the gateway. You end up with a log entry like this:

`Started new registration for subscription #18 via paypal.`

https://github.com/restrictcontentpro/restrict-content-pro/blob/2.9.6/includes/registration-functions.php#L47-L53

We had a customer think that PayPal payments were being recorded. We need to adjust the logging to avoid any confusion around that.

**Comment by nosegraze** [comment]
We also log the gateway (in this case `paypal`) in the payment we create: https://github.com/restrictcontentpro/restrict-content-pro/blob/2.9.6/includes/registration-functions.php#L213

Should we go with something like `free` or `none` instead?

**Comment by nosegraze** [comment]
PR: #1586

**Comment by pippinsplugins** [comment]
@nosegraze wouldn't this cause free trial signups through gateways to show as `free` as the gateway?

**Comment by nosegraze** [comment]
@pippinsplugins It shouldn't, because this only sets the gateway to `free` if the registration is a 100% off discount or if the subscription level price is `0`. If it's a free trial that requires a card up front, the price would be `> 0` to reflect the after-trial amount.

Just ran a quick test to confirm:

```
2017-11-30 17:07:34 - Started new registration for subscription #9 via stripe.
```
