### ISSUE TITLE
Registration form showing error for missing stripe API keys

### ISSUE THREAD

**Issue by DeveloperWil** [restrictcontentpro/restrict-content-pro#1675]
Copied register-single.php into child theme.  Was submitting a blank rego form to see what errors are returned.
Got this error in the list

"Missing Stripe test keys. Please enter your test keys to use Stripe in Sandbox Mode."

That should not be showing on the registration form.

This is on a local dev machine.  I have stripe checkout enabled and the sandbox button checked but I do not have the stripe API keys entered.

RCP Version 2.9.9

**Comment by mindctrl** [comment]
We show that error on the registration form on purpose, when the keys are missing, as a reminder to site owners to enter their keys. Believe it or not, people have tried to make payments on their sites without their keys saved in the settings. It's a useful reminder to complete the settings, and it's something their customers would likely never see... because once the site owner sees it and realizes the keys need to be entered, that's what they're going to do.

Happy to hear other ideas for improving the experience without showing on the registration form.

**Comment by DeveloperWil** [comment]
That makes sense!  Thanks for getting back to me.
