### ISSUE TITLE
Members of one subsite can log in to another subsite

### ISSUE THREAD

**Issue by tnorthcutt** [restrictcontentpro/restrict-content-pro#1699]
_I haven't spun up a new install to reproduce this in a clean environment yet; so it may be possible that this is unique to my current install._

I noticed today that members of one subsite on my multisite install are able to log into a different subsite and see/update their account details, change password, etc.

Obviously some of this has to do with WP core user account behavior. I'm curious to hear what _should_ be happening here.

**Comment by nosegraze** [comment]
Yeah this is normal behaviour in WordPress core. Since they share a user install and the whole network shares a login page/system, you can log in to any one site and be logged into them all.

I'm not really sure if this is something we should address or not. For some people this might be desirable behaviour. Given that it's a WordPress core features, it might be something you'd disable via custom code or another plugin. There's probably a way to do it.

**Comment by tnorthcutt** [comment]
Got it, thanks for clarifying.

**Comment by mindctrl** [comment]
@tnorthcutt just for clarity, were you able to see your subscription details from a different site?

**Comment by tnorthcutt** [comment]
@mindctrl yep!

**Comment by mindctrl** [comment]
Was this on the same site as #1698, where it was activated on sites individually? If so, that shouldn't happen.

**Comment by tnorthcutt** [comment]
@mindctrl yep, same multisite install as that one.

**Comment by mindctrl** [comment]
Ok, that definitely should not happen. Reopening so we dig deeper and run some tests.

**Comment by nosegraze** [comment]
Presumably it happens because the membership data is stored in `wp_usermeta`, which is global across the whole network. The thing that would be funky is a user might be on level ID `3` on one site, which is "Gold" level. But level ID `3` on another site might have a totally different name, but the same ID number.

I suspect this will naturally be fixed when we move to custom tables, because the membership info will no longer be in a global table.

**Comment by mindctrl** [comment]
Yep, that's the reason and the upcoming subscription table will fix it.
