### ISSUE TITLE
Refund remainder of annual subscription

### ISSUE THREAD

**Issue by wolffe** [restrictcontentpro/restrict-content-pro#1864]
Hi!

Currently, the annual subscription canceling works like this:

"When a member cancels their subscription, their automatic renewal payments will be immediately disabled but the member will retain access to restricted content up until the expiration date on their account is reached.

For example, if a customer's account is due to renew on June 1 and they choose to cancel on May 15th, they will be permitted to access restricted content up until June 1. Their access continues for the duration of the period they have paid for."

Is it possible to terminate the subscription immediately (or at end of month) and refund the remainder of the year?

**Comment by nosegraze** [comment]
@wolffe You can revoke access immediately by changing the user's status to `expired`. Restrict Content Pro does not have any built-in refund capabilities though, so that would have to be done via the payment gateway.

Please submit any further questions via this form: https://restrictcontentpro.com/support/ We only use GitHub for tracking our development.

Thanks!

**Comment by wolffe** [comment]
Thank you!
