### ISSUE TITLE
Add Stripe Checkout support to core

### ISSUE THREAD

**Issue by carter2422** [restrictcontentpro/restrict-content-pro#257]
As discussed on Slack I'm going to work on getting Stripe Checkout supported added to core, enabling site admins to add a signup button anywhere via shortcode. This will work alongside the regular Registration page, rather than replacing it.

**Comment by tnorthcutt** [comment]
Huge +1 from me!

**Comment by pippinsplugins** [comment]
@carter2422 Could you go ahead and submit the PR so we can start reviewing it?

**Comment by pippinsplugins** [comment]
Super excited for this :D

**Comment by carter2422** [comment]
@pippinsplugins I'll work on that PR tomorrow or later in the week :tada:

**Comment by pippinsplugins** [comment]
@carter2422 PR? :)

**Comment by carter2422** [comment]
When I get back from BCon I’ll try and finish it up.

**Comment by pippinsplugins** [comment]
Have to punt to 2.5 so I can get 2.4 out the door.

**Comment by richardtabor** [comment]
This would be fantastic! Any idea about when you're shooting to push 2.5?

**Comment by pippinsplugins** [comment]
I'd like to see it within a month or so.

**Comment by pippinsplugins** [comment]
@carter2422 Could you post the code you have for this?

**Comment by carter2422** [comment]
@pippinsplugins it's here: https://github.com/CGCookie/cgc-rcp-stripe-checkout

**Comment by pippinsplugins** [comment]
:+1:

**Comment by tannerm** [comment]
Hey everyone! I just pushed up a PR for this feature and would love to have you test it and provide any feedback. Here is the PR: #367 

There is both a new gateway (Stripe Checkout) and a Stripe Checkout shortcode [register_form_stripe]. The gateway works just like you'd expect without any extra setups.

The shortcode requires that the subscription level be identified (i.e. [register_form_stripe id="1"]). Any additional data attributes (as found here: https://stripe.com/docs/checkout#integration-simple-options) can be added to the shortcode to overwrite the default values. Here's an example:

[register_form_stripe id="2" data-image="http://example.com/wp-content/uploads/2016/02/product-image.jpg" data-description="Gold Level"]

**Comment by carter2422** [comment]
:tada:

**Comment by pippinsplugins** [comment]
@tannerm Could we pre-fill the email address when logged in? https://cloudup.com/cJpe-YYXcYN

**Comment by pippinsplugins** [comment]
Could we also add arguments to the short code to define the label of the button?

**Comment by pippinsplugins** [comment]
Looks like the redirect to the success page isn't working properly after registering through [register_form_strip]. Form was submitted and then the page reloaded.

**Comment by tannerm** [comment]
@pippinsplugins the email addresses should already be auto filled out when logged in. Let me know if you are seeing something different.

You can add the "data-label" parameter to the shortcode to specify the button text already. Do you want me to add support for an alias like "button"?

Something went screwy with the submission part of the stripe shortcode which was breaking the registration. That is now fixed and should redirect correctly.

**Comment by pippinsplugins** [comment]
I'm not seeing the email pre-populated in the Stripe checkout.

Let's do go ahead and add an alias. `data-label` isn't very intuitive for non technical users.

**Comment by tannerm** [comment]
Strange. This is what I'm seeing when logged in: https://www.dropbox.com/s/aq2yel3ap30krpk/Screenshot%202016-03-02%2010.54.31.png?dl=0

**Comment by pippinsplugins** [comment]
Looks like it is working fine now.

**Comment by tannerm** [comment]
:+1:

**Comment by pippinsplugins** [comment]
I'll do some more testing on this but I think it's about good to go!

**Comment by pippinsplugins** [comment]
Going to merge in for more thorough testing.

**Comment by pippinsplugins** [comment]
Working beautifully.

**Comment by pippinsplugins** [comment]
The email address is not getting populated when signing up from the `[register_form]` shortcode.

**Comment by michaelbeil** [comment]
It is not for me here, either.

**Comment by pippinsplugins** [comment]
Fixed.

**Comment by mindctrl** [comment]
@pippinsplugins @tannerm seeing some things with this I didn't notice earlier.

When Auto Renew is configured as "Let customer choose", the signup fee is not charged at all.

![image](https://cloud.githubusercontent.com/assets/1254870/14001500/8d0946ce-f11c-11e5-8c31-a6ab1c47bd11.png)

---

![image](https://cloud.githubusercontent.com/assets/1254870/14001525/ba590c5e-f11c-11e5-9b25-1c3aa42c93fa.png)

---

![image](https://cloud.githubusercontent.com/assets/1254870/14001580/1020d176-f11d-11e5-895b-96022436adb1.png)

---

![image](https://cloud.githubusercontent.com/assets/1254870/14001587/215ca9f6-f11d-11e5-8cba-a87ce3b8c74d.png)

--

#### If you change Auto Renew to "Always", the signup fee *is* charged, but it's not reflected in the price listed on the Register button in the modal.

![image](https://cloud.githubusercontent.com/assets/1254870/14001647/810dd280-f11d-11e5-9313-e1f1a0177968.png)

---

![image](https://cloud.githubusercontent.com/assets/1254870/14001650/869ead6e-f11d-11e5-91c6-449a5a465601.png)

---

![image](https://cloud.githubusercontent.com/assets/1254870/14001662/95ada6ac-f11d-11e5-86b6-f14ca7448095.png)

---

![image](https://cloud.githubusercontent.com/assets/1254870/14001674/a5b4cc06-f11d-11e5-81f1-5821a5fbf84f.png)

---

#### If you then change to another subscription using Stripe Checkout, the only charge is the signup fee.

![image](https://cloud.githubusercontent.com/assets/1254870/14001742/04a138ee-f11e-11e5-81b2-5bd7178d6f68.png)

---

![image](https://cloud.githubusercontent.com/assets/1254870/14001777/2ea2ef7a-f11e-11e5-8b60-6f4ab841bffc.png)

---

![image](https://cloud.githubusercontent.com/assets/1254870/14001783/3c942234-f11e-11e5-9e69-abb27bad7606.png)

---

#### During one test I bought the same subscription I already had, and it ended up charging me just the signup fee and cancelled the subscription in RCP. This only happened once, but something to look at.

![image](https://cloud.githubusercontent.com/assets/1254870/14001912/e797e544-f11e-11e5-9f02-17ca115a3b67.png)

---

![image](https://cloud.githubusercontent.com/assets/1254870/14001925/f7df4a14-f11e-11e5-8ccb-1fc65507ef5c.png)

---

#### If you go from one subscription to another that has a negative signup fee, there is no charge made but the member's subscription is changed in RCP but not in Stripe. The negative signup fee is what's shown in the popup. In the screenshots below, the member had a $10 subscription and moved to a $20 sub with a $-5 signup fee.

![image](https://cloud.githubusercontent.com/assets/1254870/14002440/7153c660-f122-11e5-9d20-b60dc516fa26.png)

---

![image](https://cloud.githubusercontent.com/assets/1254870/14002442/7624605a-f122-11e5-85a9-da8aaf23fe7d.png)



Summary:
- Signup fees seem to only be charged when Auto Renew is set to Always.
- Signup fees are not reflected in the price on the button in the popup.
- When going from one subscription to another, the only charge is the signup fee. The subscription price is not billed.
- When going from one subscription to another that has a negative signup fee, there is no charge, the member's level is changed in RCP but not in Stripe. Not this seems to be the only time the signup fee shows in the popup.

**Comment by pippinsplugins** [comment]
Good testing!

I'll work on addressing these tomorrow.

**Comment by mindctrl** [comment]
I'm going to have to retest the ones with "Platinum Grill" involved. I had the price and signup fee backwards.

**Comment by pippinsplugins** [comment]
I'm not sure we can really support pro-ration on stand alone Stripe checkout.

Anyone opposed to disabling it automatically for users with an active subscription? They can be forced to go through the standard registration form for upgrades. We can have it documented.

**Comment by pippinsplugins** [comment]
To address:

- [ ] Signup fees seem to only be charged when Auto Renew is set to Always.
- [ ] Signup fees are not reflected in the price on the button in the popup.
- [ ] When going from one subscription to another, the only charge is the signup fee. The subscription price is not billed.
- [ ] If you're crazy enough to purchase the same subscription you already have, you get charged for the signup fee and cancelled. The charge makes since with proration I think, but not cancellation. Can we prevent people from doing this? Edge case.
- [ ] When going from one subscription to another that has a negative signup fee, there is no charge, the member's level is changed in RCP but not in Stripe. Note this seems to be the only time the signup fee shows in the popup.

**Comment by mindctrl** [comment]
I'm not opposed to disabling Checkout for active subscribers. 

What do you think about moving this into the existing [register_form] shortcode and make it an attribute instead of a whole new shortcode? That would make it much less confusing for site owners I think. Another benefit would be if someone disables Stripe, they don't have to change their shortcodes. We can simply go straight to the registration page.

**Comment by michaelbeil** [comment]
Quoting @mindctrl regarding a register_form Stripe Checkout attribute:

> for example, in EDD it's the `direct=true` option in [purchase_link]. in RCP it's [register_form_stripe], and I think it could be [register_form stripe_checkout=true] or something like that.

**Comment by michaelbeil** [comment]
Re @pippinsplugins:

> Anyone opposed to disabling it automatically for users with an active subscription? They can be forced to go through the standard registration form for upgrades. We can have it documented.

- [x] Not opposed
- [ ] Opposed

**Comment by pippinsplugins** [comment]
>>>What do you think about moving this into the existing [register_form] shortcode and make it an attribute instead of a whole new shortcode? 

I rather like having two short codes actually because they are quite different experiences.

The `[register_form]` shortcode supports both regular Stripe (with the full card input fields) and Stripe Checkout.

The `[register_form_stripe]` is only Stripe.

So why a separate form for Stripe only? Simple: it's a completely different experience. With the standard `[register_form]` shortcode, customers enter their full account and payment details, but with `[register_form_stripe]`, customers only enter their email address and their payment details. It's an expedited process.

Another reason I see for keeping them separate is that there is no replacement for the stand alone Stripe Checkout form. We can't just replace a single button with an entire registration form in the case that someone stops using Stripe.

To emulate the behavior that we have in EDD with the standard `[register_form]` shortcode, site owners simply enable the `Stripe Checkout` option in payment gateways instead of the regular `Stripe` option. That will display the Stripe Checkout modal on the `[register_form]`.

**Comment by pippinsplugins** [comment]
Regarding this issue:

>>>Signup fees seem to only be charged when Auto Renew is set to Always.

Signup fees have never been charged on non-recurring purchases, mostly because the idea of a signup fee + onetime purchase is a bit odd. Probably ways to handle it but I'd say that's outside the scope of this issue since it has always been that way and it is that way in all gateways.

I propose that we force stand alone Stripe Checkout to use auto renew if the auto renew setting is set either `Let customers choose` or `Always auto renew`. If it is set to `never`, we'll force it to a one time.

**Comment by pippinsplugins** [comment]
Ok auto renew behavior should work as expected now.

**Comment by michaelbeil** [comment]
- [x] on signup fees. that is another behemoth to tackle later.

So, Stripe Checkout would always auto renew, unless auto renew is unchecked?

**Comment by pippinsplugins** [comment]
>>> So, Stripe Checkout would always auto renew, unless auto renew is unchecked?

The stand alone Stripe Checkout form, yes.

**Comment by michaelbeil** [comment]
Makes perfect sense.

**Comment by pippinsplugins** [comment]
@mindctrl Could you test the last three bullet points again? I'm not sure they still apply.

**Comment by pippinsplugins** [comment]
Instead of showing the Stripe Checkout button: https://cloudup.com/cQPXBWExISN

**Comment by pippinsplugins** [comment]
Pretty sure we're done with this now.

**Comment by pippinsplugins** [comment]
Stripe Checkout is not properly supporting the `Auto Renew` checkbox on the registration page.

**Comment by pippinsplugins** [comment]
Fixed.

**Comment by pippinsplugins** [comment]
Stripe Checkout fails when `id` is passed to `[register_form]` like `[register_form id="2"]`. It generates a javascript error.
