### ISSUE TITLE
Show membership level and content to member via shortcode

### ISSUE THREAD

**Issue by sumobi** [restrictcontentpro/restrict-content-pro#258]
Members are redirected to the welcome page when they register for a membership level, or when they renew a subscription. It would be nice to be able to use a shortcode on the welcome page that outputs the member's current level. Eg:

> Thanks for signing up to our Pro membership. The pro membership includes everything you'll ever need, we know you'll enjoy it!

and for renewals:

> Thanks for renewing your Pro membership!

Based on the above, it would also be handy to show different blocks of content based on the member level. This would allow the site owner to fine-tune the text so it's specific to the membership level.

I'd suggest 2 shortcodes, one that uses the `rcp_get_subscription()` function to output the current membership text, and 1 to wrap content in. The site owner for example might like to show a list of links to posts and pages that the member can access straight away.

**Comment by carter2422** [comment]
:+1: from me!

**Comment by chuckreynolds** [comment]
To me it just looks like we'd need a `[member_level_name]` shortcode that just spits out the membership level name.  Extend `[subscription_details]` maybe?

The messaging content, imo, could be wrapped with shortcodes currently available. 
Example: 
```[restrict subscription="333"]Thanks for signing up to our [member_level_name] [/restrict]```

Because there's only one field, currently, for the membership name there may be some filters needed... for example all of mine are like `active-member` & `awaiting-auth-accept... I use it more as a unique slug sort of thing as opposed to assuming spaces and caps will work in code when I'm trying to restrict stuff. In that case, using the same field, something like converting first letter to caps and replacing dashes with spaces... but that could mess people up too.

Perhaps the better answer is to add another meta field to rcp-member-levels page that would be optional and only for front-end echoing, not user restriction, and apply that to the [member_level_name] shortcode.

**Comment by pippinsplugins** [comment]
I'd think the best option, at least to start, is just a single shortcode like @chuckreynolds mentioned. That way it can be used inside of a paragraph.

>>>Thank you for signing up for our [member_subscription_name]!

**Comment by sumobi** [comment]
:+1:

**Comment by tannerm** [comment]
I just created a pull request (#372) that adds shortcodes for a user's subscription id ([subscription_id]),  subscription name ([subscription_name]), and expiration date ([user_expiration]). Let me know if you have any thoughts or feedback. // cc @pippinsplugins

**Comment by pippinsplugins** [comment]
Looks great!

**Comment by sumobi** [comment]
Sweet!
