### ISSUE TITLE
Stripe: add support for prorating plans

### ISSUE THREAD

**Issue by carter2422** [restrictcontentpro/restrict-content-pro#304]
If a user re-upgrades while a previous Plan is active Stripe will attempt to prorate the plan, while RCP will also charge the full amount. This leads to customers being charged more than they should be even at full rate. 

![screen shot 2015-12-10 at 10 41 00 am](https://cloud.githubusercontent.com/assets/1648631/11721684/a60a5e7c-9f2a-11e5-96cb-8f71dd73d9ec.png)

We need to add support for prorating.

**Comment by carter2422** [comment]
This appears to be more than an issue of proration; I think it's more related to an unpaid plan with time remaining on it. Investigating further.

**Comment by pippinsplugins** [comment]
RCP intentionally does not modify the charged amount.

That's where  #195 comes into play.

**Comment by tannerm** [comment]
@carter2422 @pippinsplugins I think I found the issue here while investigating #302. 

If the account in Stripe is "past_due" and then the user upgrades/downgrades then they are charged for the past_due invoice and then prorated to the new subscription.

This happens because the card data is saved before the subscription is switched. The PR I'm going to submit should address both of these issues.

**Comment by pippinsplugins** [comment]
@tannerm sounds right. Left two notes on the PR for you, one question and one tweak.

**Comment by carter2422** [comment]
Good find @tannerm!

**Comment by tannerm** [comment]
Global support for prorating has been added to PR #356. @carter2422 and @pippinsplugins can you guys test when you get a chance?

**Comment by carter2422** [comment]
@tannerm I'll try and test tomorrow!

**Comment by pippinsplugins** [comment]
This is all working really well. A few minor items to address over on #195 but otherwise good to go.

**Comment by carter2422** [comment]
:tada:
