### ISSUE TITLE
Failed payment emails

### ISSUE THREAD

**Issue by pippinsplugins** [restrictcontentpro/restrict-content-pro#360]
We should add support for failed payments so that customers can be alerted when their payments are failing to be processed.

**Comment by michaelbeil** [comment]
This would be good.

**Comment by mindctrl** [comment]
Just had another request for this.

**Comment by nosegraze** [comment]
Got a request for this today.

**Comment by mindctrl** [comment]
Another request for emailing on failed charges.

**Comment by pippinsplugins** [comment]
I've added in a new `rcp_recurring_payment_failed` hook that is fired by all gateways whenever a recurring payment fails.

Will wait to finish the actual email process until #748 is finished.

**Comment by pippinsplugins** [comment]
@mindctrl could you take over on this now that `RCP_Emails` has been merged?

**Comment by mindctrl** [comment]
👍 will do.

**Comment by mindctrl** [comment]
After letting this run for several more days, I'm seeing an issue we need to address. With the way Stripe (and possibly other gateways) work, invoices keep piling up when expired, at least for some period of time. Looking back at this particular test customer, my failed invoices have been piling up daily since 11/01/16.

In my tests of a daily subscription, each day that passes a new invoice is created and payment attempts are made for the new invoice and several of the past invoices (not all past invoices it seems). This results in a bunch of webhooks coming in for each failed attempt, within seconds of each other, and an email is sent for each one.

In my Stripe account, I have it set up to attempt 3 charges and then cancel.
![image](https://cloud.githubusercontent.com/assets/1254870/21584569/8e7de9fe-d07a-11e6-8558-533fbefc9a0c.png)

However the subscription is "past due", not cancelled, and new invoices keep being created. We should probably deal with this in some way to ensure subscriptions really get cancelled after a period of time, in a separate issue, but I think in the meantime we should put some kind of limit on the number of failed payment emails we send.

I'm reopening this issue to deal with the email part of it.

**Comment by pippinsplugins** [comment]
Was this subscription failing before you set it to 3 charge attempts?

**Comment by mindctrl** [comment]
@pippinsplugins I already had the 3 charge attempts set up before this customer. I've had it that way for as long as I can remember. No idea why Stripe isn't properly cancelling it.

**Comment by pippinsplugins** [comment]
@mindctrl I'm not sure this is an issue we need to address; that's really a Stripe problem.

I vote we not worry about this for the time being. If it becomes a problem, we can reassess. We don't prevent repeated sends in EDD Recurring Payments and have so far not had a single report of a problem.

**Comment by mindctrl** [comment]
@pippinsplugins sounds good to me. Closing.
