### ISSUE TITLE
Wrong default currency for fees/discounts (Stripe)

### ISSUE THREAD

**Issue by tannerm** [restrictcontentpro/restrict-content-pro#382]
This is probably a pretty obscure bug. If a user's Stripe account is set to a default currency other than the one specified in RCP, then RCP will use the wrong currency when setting an initial fee and the user charge process will error with:

> Stripe::InvalidRequestError (Can't combine currencies on a single customer. This customer has had a subscription, coupon, or invoice item with currency us)

**Comment by pippinsplugins** [comment]
Oh! I think I ran across that the other day

**Comment by pippinsplugins** [comment]
I've tracked this down.

It's due to the `account_balance` feature of the customers API. Turns out that the account_balance does not support a currency option, so it will always be in the currency of the default account's currency. That then triggers an error if you try and subscribe a customer in a non-default currency with a signup fee or pro-ration.

At this time I don't believe there is a way to resolve this. We've run into this with EDD as well.

**Comment by nosegraze** [comment]
Is there still not a way to resolve this? I have a new customer with this problem and just want to confirm.

**Comment by pippinsplugins** [comment]
@nosegraze see https://github.com/easydigitaldownloads/edd-recurring/issues/813

**Comment by mindctrl** [comment]
Stripe supports a currency setting when creating plans, which we do. If the plan was created in Stripe before the RCP currency was changed, it won't work due to the currency mismatch.

This should work:
- Set Stripe account to USD
- Configure RCP to EUR
- Create new level in RCP
- Register for the new level, let RCP create the plan with the EUR currency (`RCP_Payment_Gateway_Stripe::create_plan()`), and it should work.

**Comment by pippinsplugins** [comment]
And https://github.com/easydigitaldownloads/edd-recurring/issues/763

**Comment by pippinsplugins** [comment]
Ok I have this working now.

To replicate:

1. Set your RCP site to a currency other than your Stripe account's default. I set my site to use EUR as my Stripe account uses USD.
2. Checkout `master`
3. Create a discount code
4. Register for a recurring membership through Stripe after applying your discount
5. It will fail while creating the subscriptionn

To test:

1. Repeat steps above
2. Registration will go through successfully

Note, there is one caveat here. The plan IDs that we setup in RCP do not currently take currency codes into account, so this fix will only work for _new_ plans created. I don't think this is really a problem as it will only happen to sites that change their currency coded (uncommon) after already having plans setup. If we do want to resolve it, we'll need to update the logic in `plan_exists()` to take currency into account.

**Comment by nosegraze** [comment]
This worked for me. I'm sending the PR to a customer to confirm.

**Comment by nosegraze** [comment]
Got confirmation from the customer that this fixed the problem. Merged!

**Comment by pippinsplugins** [comment]
:tada:
