### ISSUE TITLE
Amounts over 1,000 converted to 1 on some sites

### ISSUE THREAD

**Issue by pippinsplugins** [restrictcontentpro/restrict-content-pro#459]
I've seen two reports of this so far. Numbers over `1000` are getting displayed as a single digit number on the frontend.

Appears to be caused by the changes with `number_format` introduced in #436

**Comment by michaelbeil** [comment]
Is this with specific currencies?

**Comment by mindctrl** [comment]
#436 introduced this, but I think we should go deeper into the registration class to fix it. For example. when returning `get_recurring_total()`, it passes through `number_format`. This causes it to become a formatted string, which then gets stripped when passing through `number_format` again with the changes from #436.

I don't think we should be formatting the amounts returned from the registration class, since they may need to have additional operations run against them, formatted for other currencies, etc.

Thoughts?

**Comment by pippinsplugins** [comment]
I agree, formatting should only ever happen immediately before output. Never before.

**Comment by mindctrl** [comment]
@michaelbeil could use some testing on this. I tried various total formats... 4.90, 4.00, 1000, and so on. Could you run some tests to see if you can break the display of any totals?

**Comment by pippinsplugins** [comment]
At first glance this looks correct.

**Comment by michaelbeil** [comment]
Can do @mindctrl.

**Comment by michaelbeil** [comment]
All checks out well here.

**Comment by michaelbeil** [comment]
Still good after last commit. Even better, actually.
