### ISSUE TITLE
Introduce RCP_Emails

### ISSUE THREAD

**Issue by pippinsplugins** [restrictcontentpro/restrict-content-pro#748]
It is time RCP had a nice emails class to handle email delivery and templates. This will also allow us to easily introduce HTML emails.

**Comment by pippinsplugins** [comment]
WIP submitted.

**Comment by pippinsplugins** [comment]
I've only done very minimal testing on it but I believe this is now ready for real testing.

**Comment by pippinsplugins** [comment]
Template tags are not working during payment received though not sure why.

![screen shot 2016-12-10 at 11 00 41 pm](https://cloud.githubusercontent.com/assets/1034109/21078195/87a901ea-bf2c-11e6-97a0-7289942bd32a.png)

**Comment by pippinsplugins** [comment]
Email tags fixed!

@mindctrl @nosegraze could I get some tests on this? I think it's about done.

A few items to pay attention to:

1. There is now an `Email Header` option in the Emails tab of settings
2. There is now an `Email Logo` option in the emails tab of settings
3. Every email template tag needs tested
4. We now have actual template files for emails
5. Please test it with an extension, such as Groups, that registers new email template tags

**Comment by nosegraze** [comment]
I've only done a first pass so far - I'll come back and look at it more thoroughly later today (and test with groups). But here are some initial notes:

The email logo field text should be updated to "Email Logo" (it's currently "Email Header" -- same as the email header field).

![rcp-email-header](https://cloud.githubusercontent.com/assets/6324272/21099036/f0546f80-c063-11e6-8c4b-6254773ec3fa.png)


For the `emails/header-default.php` template, I'm thinking we should only display this section: https://github.com/restrictcontentpro/restrict-content-pro/blob/issue/748/templates/emails/header-default.php#L85-L97 if `$header_text` isn't empty. Otherwise if someone leaves it blank, it results in a huge blank space in the final email.

This may actually be unrelated to your update, but I noticed that when registering for a free plan, `%amount%` shows up as just `$`. IMO it should say `$0`.

![rcp-email-tag-amount](https://cloud.githubusercontent.com/assets/6324272/21099089/34205cd8-c064-11e6-9d06-a6093bf97143.png)

**Comment by nosegraze** [comment]
Just tested it with groups and all template tags work!

**Comment by pippinsplugins** [comment]
Yay!

**Comment by pippinsplugins** [comment]
Setting label fixed and header text section is only shown if the value is set.

**Comment by mindctrl** [comment]
We need to make the `wp_editor` windows wider, but the wrapping container is fixed width to allow the email tags to be displayed next to it.

![image](https://cloud.githubusercontent.com/assets/1254870/21240685/68b64520-c2da-11e6-895b-03f057a93e28.png)

I'm going to look at improving the layout a bit.

**Comment by mindctrl** [comment]
@pippinsplugins thoughts on this? Moved the template tags into the other container, above all the individual email settings. That allows us to just let the emails settings container expand with the page and also works a lot better on tablet/mobile.

![image](https://cloud.githubusercontent.com/assets/1254870/21242822/1cf6a42c-c2e4-11e6-9037-218a22786d3b.png)

**Comment by pippinsplugins** [comment]
I'm good with that approach.

**Comment by Basilakis** [comment]
Hey,

Does it support Full HTML or there is a template folder which we can overwite through templates and modify HTML?

Preparing for theme compatibility.

Thank u

**Comment by pippinsplugins** [comment]
Yes, it's full HTML with editable template files.

**Comment by pippinsplugins** [comment]
@mindctrl happy with this? If so I will go ahead and merge and close.

**Comment by mindctrl** [comment]
Going to give this another test this afternoon/evening and will comment when done.

**Comment by mindctrl** [comment]
When adding a custom template with the `rcp_email_templates` filter, if you don't supply all 3 templates files(header, body, and footer), parts of the email won't load.

To clarify, say you only want to customize the header of your email. You select the custom template from the dropdown and save. In this case the template is `moo`. You drop in a `header-moo.php` file. You do not supply a body or footer for `moo`. When `get_template()` returns the name for `rcp_get_template_part`, the fallback body-default.php and footer-default.php will not be loaded and the body will be empty.

I think the best fix is probably to rename the template files to remove the `-default` suffix from all of them and change the default return value in `get_template()`. Thoughts?

**Comment by pippinsplugins** [comment]
Yes, removing `-default` should work I'd think.

**Comment by mindctrl** [comment]
Getting a PHP warning when trying to email. I think it's related to the `%amount%` tag. Going to dig into it.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by mindctrl** [comment]
This happens because we never set up the `$payment_id` property in `RCP_Emails` and so it doesn't get passed to `rcp_email_tag_amount()`. We could set it up in the `send()` method, only if it hasn't already been set, by querying the last payment of the member.

We should probably also separately get the last payment ID of a member in `rcp_email_tag_amount()` is a payment ID is not passed in.

Thoughts?

**Comment by pippinsplugins** [comment]
>>>We could set it up in the send() method, only if it hasn't already been set, by querying the last payment of the member.

:+1:

**Comment by pippinsplugins** [comment]
@mindctrl does that finish it up?

**Comment by mindctrl** [comment]
@pippinsplugins I think so. If I find anything else I'll open a new issue.

**Comment by pippinsplugins** [comment]
Let's merge and close then!
