### ISSUE TITLE
Option to show excerpts by default

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#763]
I've gotten two requests now to have a way to enable excerpts for non-members by default without having to select the option each time.

**Comment by opt1k4l** [comment]
would love to see this too.  looked all over for it in the documentation and then stumbled upon this enhancement.

**Comment by nosegraze** [comment]
I got another request this week and I've been thinking about how to approach this. Maybe we should add a new global "Content Excerpts" setting that has a dropdown with three options:

1. Always show excerpts
2. Never show excerpts
3. Decide for each post individually

If 1 or 2 is chosen then we hide the checkbox from the post metabox (and maybe show text instead reminding them of their chosen setting). If they choose 3 then we show the checkbox as we do now.

**Comment by pippinsplugins** [comment]
I like that approach.

**Comment by nosegraze** [comment]
PR: #997

**Comment by mindctrl** [comment]
PR looks good. A thought about the UI on the post edit screen.

When the global option is set to show/hide, you get a sentence like this:

![image](https://cloud.githubusercontent.com/assets/1254870/23131355/b01022fe-f757-11e6-8334-63f32d46a77b.png)

It looks like a description instead of an option, which is ok. But what do you think about something like this?

![image](https://cloud.githubusercontent.com/assets/1254870/23131394/d1eb15fa-f757-11e6-884f-e057b74cc415.png)

In that example, the global setting is enabled. The checkbox would be checked, but disabled, to keep the UI layout consistent and to show at a quick glance what the setting is. If it were disabled, it would be unchecked and disabled. The tooltip could reveal the hint about the global setting.

Thoughts?

**Comment by nosegraze** [comment]
Yes, I love that! That's a much better idea.

**Comment by mindctrl** [comment]
I think you'd need to check the global setting during save, the avoid saving the individual meta value if globally disabled/enabled... just to avoid adding more post meta when it's not needed.

**Comment by pippinsplugins** [comment]
Love it.

**Comment by mindctrl** [comment]
Works great. Made some minor adjustments and merged.
