### ISSUE TITLE
Possible duplicate subscription when a card expires after initial signup

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#779]
> Credit Card fails -- > User than Updates Payment Card --> Then seems like ANOTHER subscription gets made ?? Only happens when this expiration or CC is declined... ( Payment fails ) then user updates card..

Haven't been able to test/verify this yet. Tricky circumstances as it seems like you have to:

* Sign up for a recurring payment with a valid card.
* Have that card expire and payment fail.
* User updates the card to a valid one.

References:
https://secure.helpscout.net/conversation/193846630/32504/?folderId=841781
https://secure.helpscout.net/conversation/278933415/46980/

**Comment by pippinsplugins** [comment]
@nosegraze sounds like the customer's account failed to rebill due to an expired card and then, instead of using the update payment method, the customer bought a new subscription with a different card. Doing this caused the account in Stripe to be billable again and so charged the customer for both subscriptions.

**Comment by nosegraze** [comment]
Good point, that's definitely a possibility. I'll check back in with him about that.

**Comment by nosegraze** [comment]
> They say they are NOT.. but It has happened 4 times..
> Expired Failed payment
> Update card in RCP and then gets a new Stripe subscription… ?

Hrrrm.

**Comment by nosegraze** [comment]
Update:

The card expired, I updated it, and no second subscription was created.

I checked back in with the guy who reported it to confirm he definitely got a second subscription created (rather than like a second payment for the same subscription) and he said yes. So, in short, I wasn't able to reproduce his problem. I ended up with only the one original subscription.

![rcp-stripe](https://cloud.githubusercontent.com/assets/6324272/20859293/8c05f8b8-b952-11e6-8956-7d96c53b3320.png)

**Comment by pippinsplugins** [comment]
Are we certain the customer of the site in the related tickets actually used the `Update payment method` form? It sounds to me like the customer clicked the "Upgrade or renew subscription" link and simply purchased a new subscription instead of updating the card. Doing that would result in the exact behavior reported.

**Comment by nosegraze** [comment]
That's what I'm thinking. Though I asked the guy and he says the customers swear they didn't do that, so.. *shrugs*

**Comment by pippinsplugins** [comment]
Closing as invalid unless we receive further evidence of there being a real issue here.
