### ISSUE TITLE
Replace &amp; with & in PayPal query string

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#785]
Make sure we always use `&` in query strings and don't end up with `&amp;` or spend an hour wondering why nothing works.

From EDD:

`$paypal_redirect = str_replace( '&amp;', '&', $paypal_redirect );`

**Comment by chriscct7** [comment]
This actually is caused by HostEurope and a couple other bad-actor hosts changing the `arg_seperator.output` PHP ini setting from the default `&` to `&amp;`. This setting is used in PHP core functions like `http_build_query` and a couple other functions and the change breaks the function from creating a redirectable url. https://wordpress.org/plugins/reset-arg-seperator-output/ can also fix this for those affected. Also you can detect the breakage when using Core Control's HTTP Access Logger functionality

**Comment by chriscct7** [comment]
Opened an issue on EDD to correctly fix the issue: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5256

**Comment by chriscct7** [comment]
RCP has the same use that EDD does, so all it needs to do is add a ` '', '&'` to the `http_build_query` call in the PayPal library, just like EDD core.

**Comment by pippinsplugins** [comment]
PR submitted.

**Comment by chriscct7** [comment]
Huh, the way that should be fixed is using:
$paypal_redirect .= http_build_query( $paypal_args, '', '&' );

which is how we're fixing it in EDD core.

**Comment by pippinsplugins** [comment]
@chriscct7 I'm doing it exactly like we have in EDD core and the way it's been working perfectly for 2+ years.
