### ISSUE TITLE
Cache and subscription level

### ISSUE THREAD

**Issue by madvik** [restrictcontentpro/restrict-content-pro#790]
When you delete a subscription level , the cache is not update. And we have a ghost subscription on front.
To solve the solution, I delete `object-cache.php`

**Comment by pippinsplugins** [comment]
Related #643

**Comment by mindctrl** [comment]
Related: https://github.com/restrictcontentpro/restrict-content-pro/issues/646

**Comment by mindctrl** [comment]
I think we should move this to the Transients API. Out of the box, `WP_Object_Cache` data doesn't persist unless there's a persistent caching plugin installed on the site.

The transients API will use persistent caching if there is one installed, otherwise it gets cached in the options table. This would at least give us some caching on a large number of sites that don't have persistent caching installed, and change nothing for those that do.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by pippinsplugins** [comment]
Going to move this to 2.7.5 as it's not super important.
