### ISSUE TITLE
Don't send 'activated' emails to new trial accounts

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#882]
When a new user registers for a free trial, they get both the 'activated' and 'trial' emails. IMO they should only be getting the trial one.

**Comment by nosegraze** [comment]
PR: #947

**Comment by mindctrl** [comment]
This only happens on free trials that are the old style, with zero cost and a limited duration... not the new trials. Is that right?

And it looks like the new free trial method in 2.7 doesn't send an email to the member at all, because `rcp_email_subscription_status` returns early in the `active` case because `rcp_is_trialing` is true.

**Comment by nosegraze** [comment]
That's correct. This is only for old free trials.

See #935 for new free trial issue.

**Comment by pippinsplugins** [comment]
I vote we not fix it for the old method. That method should get 100% removed as we move forward.
